2.1 파이토치 개요
1) 파이토치의 특징 및 장점 : GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임 워크

*note* 벡터. 행렬. 텐서
1. 1차원 축(행) : 벡터
2. 2차원 축(열) : 행렬
3. 3차원 축(채널) : 텐서

파이토치 API
1. torch : GPU를 지원하는 텐서 패키지
2. torch.autograd : 자동미분 패키지
3. torch.nn : 신경망 구축 및 훈련 패키지
4. torch.multiprocessing : 파이썬 멀티프로세싱 패키지
5. torch.utils : DataLoader 및 기타 유틸리티를 제공하는 패키지

2.2 파이토치 기초 문법

텐서 생성 및 변환

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]])) #2차원 형태의 텐서 생성
#print(torch.tensor([[1,2],[3,4]], device="cuda:0")) #GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) #dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [2]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0],temp[1],temp[-1]) #인덱스로 접근
print(temp[2:5],temp[4:-1]) #슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])


In [3]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w-v) #길이가 같은 벡터간 뺄셈 연산

tensor([2, 2, 3])


2) 데이터 준비

In [ ]:
#단순한 파일을 불러와서 사용
import pandas as pd
immport torch
data = pd.read_csv('car_evaluation.csv')
x=torch.from_numpy(data['x'].values).unsqueeze(dim=1).float() #csv 파일의 x 칼럼의 값을 넘파이 배열로 받아 tensor로 바꾼다
y=torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

In [ ]:
#커스텀 데이터셋을 만들어서 사용
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self): #필요한 변수를 선언하고 데이터 셋의 전처리를 해주는 함수
    def __len__(self): #데이터셋의 길이, 즉 총 샘플의 수를 가져오는 함수
    def __getitem__(self,index) : #데이터셋에서 특정 데이터를 가져오는 함수

In [4]:
#파이토치에서 제공하는 데이터셋 사용
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,),(1.0,))
]) #평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포를 조정

from torchvision.datasets import MNIST
import requests

In [6]:
download_root='/data/MNIST_DATASET' #내려받을 경로 지정

train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

100%|███████████████████████████████████████████████████████████████████| 9912422/9912422 [00:01<00:00, 8522971.50it/s]


Extracting /data/MNIST_DATASET\MNIST\raw\train-images-idx3-ubyte.gz to /data/MNIST_DATASET\MNIST\raw



100%|██████████████████████████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 14450160.30it/s]


Extracting /data/MNIST_DATASET\MNIST\raw\train-labels-idx1-ubyte.gz to /data/MNIST_DATASET\MNIST\raw



100%|███████████████████████████████████████████████████████████████████| 1648877/1648877 [00:00<00:00, 4985353.24it/s]


Extracting /data/MNIST_DATASET\MNIST\raw\t10k-images-idx3-ubyte.gz to /data/MNIST_DATASET\MNIST\raw



100%|█████████████████████████████████████████████████████████████████████████| 4542/4542 [00:00<00:00, 4533681.29it/s]

Extracting /data/MNIST_DATASET\MNIST\raw\t10k-labels-idx1-ubyte.gz to /data/MNIST_DATASET\MNIST\raw



3. 모델 정의

- 계층 : 모듈 또는 모듈을 구성하는 한 개의 계층으로 합성곱층, 선형 계층 등이 있음
- 모듈 : 한 개 이상의 계층이 모여서 구성된 것. 모듈이 모여 새로운 모듈을 만들 수 있음
- 모델 : 최종적으로 원하는 네트워크. 한 개의 모듈이 모델이 될 수도 있다

In [8]:
#단순 신경망을 정의하는 방법
import torch.nn as nn
model = nn.Linear(in_features=1, out_features=1, bias=True)

In [11]:
#nn.Module()을 상속하여 정의하는 벙법
class MLP(ModuleName):
    def __init__(self, inputs):
        super(MLP, self).__init__()
        self.layer=Linear(inputs, 1)
        self.activation = Sigmoid()
        
    def forward(self, X):
        X = self.layer(X)
        X = self.activation(X)
        return X

In [13]:
#Sequential 신경망을 정의하는 방법
import torch.nn as nn
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))
        
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))
        
        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True))
        
        def forward(self, x):
            x = self.layers1(x)
            x = self.layers2(x)
            x = x.view(x.shape[0],-1)
            x = slf.layer3(x)
            return x
        
model = MLP()

print("Printing childeren\n-----------------------")
print(list(model.children())) #class MLP 아래 수준의 노드 반환
print("\n\nPrinting Modules\n---------------------")
print(list(model.modules()))

#nn.Sequential은 모델의 계층이 복잡할수록 효과가 뛰어나다

Printing childeren
-----------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
---------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=7

In [14]:
#함수로 신경망을 정의
#재사용 할 수 있는 장점 있지만 모델이 복잡해진다는 단점도 있음

def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_feature=out_features, bias=True)
    net = nn.Sequential(hiddem, activation, output)
    return net

#ReLU, Softmax 및 Sigmoid와 같은 활성화 함수는 모델을 정의할 때 지정

4. 모델의 파라미터 정의

1. 손실함수 : 학습하는 동안 출력과 실제 값 사이의 오차를 측정 
  - BCELoss : 이진분류
  - CrossEntropyLoss : 다중클래스 분류
  - MSELoss : 회귀모델
2. 옵티마이저 : 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법을 결정. step() 메소드를 통해 전달받은 파라미터 업데이트.
  - torch.optim.Optimizer(params, defaults): 모든 옵티마이저의 기본이 되는 클래스
  - zero_grad() : 옵티마이저에 사용된 파라미터들의 기울기를 0으로 만듬
  - torch.optim.lr_scheduler : 에포크에 따라 학습률을 조정할 수 있음
  - 옵티마이저의 종류: Adadelta, Adagrad, Adam, SparesAdam, Adamx, ASGD, LBFGS, RMSProp, Rprop, SGD
3. 학습률 스케줄러 : 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소. 최적점을 찾아갈 수 있게 해준다
  - optim.lr_scheduler.LambdaLR : 람다 함수를 이용하여 결과를 학습률로 설정
  - optim.lr_scheduler.StepLR : 특정 단계마다 학습률을 감마 비율만큼 감소
  - optim.lr_scheduler.ExponentialLR : 에포크마다 이전 학습률에 감마만큼 곱함
  - optim.lr_scheduler.CosineAnnealingLR : 학습률을 코사인 함수의 형태처럼 변화. 학습률이 커지기도 작아지기도 함
  - optim.lr_scheduler.ReduceLROnPlateau : 학습이 잘 되고 있는지 아닌지에 따라 동적으로 학습률을 변화
4. 지표 : 훈련과 테스트 단계를 모니터링

In [21]:
#모델의 파라미터를 정의하는 예시 코드
import torch
from torch.optim import optimizer
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95**epoch)
for epoch in range(1, 100+1): #에포크수만큼 데이터를 반복하여 처리
    for x, y in dataloader : #배치 크기만큼 데이터를 가져와서 학습 진행
        optimizer.zero_grad()
loss_fn(model(x),y).backward()
optimizer.step()
scheduler.step()

NameError: name 'dataloader' is not defined

5. 모델훈련

파이토치 학습 절차
- 모델, 손실 함수, 옵티마이저 정의
- optimizer.zero_grad(): 전방향 학습, 기울기 초기화
- output = model(input) : 출력계산
- loss = loss_fn(output, target) : 오차 계산
- loss.backward() : 역전파 학습
- optimizer.step() : 기울기 업데이트

6. 모델평가

In [34]:
import torch
import torchmetrics
#원래 코드
preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target) #모델평가를 위해 torchmetrics, functional.accuracy 사용


TypeError: accuracy() missing 1 required positional argument: 'task'

In [38]:
import torch
import torchmetrics

num_classes = 5

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target, task='multiclass', num_classes=num_classes)


In [ ]:
#모듈을 이용하여 모델을 평가하는 코드
####원래 코드###
import torch
import torchmetrics
metric = torchmetrics.Accuracy()

n_batches = 10
for i in range(n_batches):
    preds = torch.rand(10,5).softmax(dim=-1)
    target = torch.metrics(5,(10,))
    
    acc = metric(preds, target)
    print(f"Accuracy on batch : {i} : {acc}") #현재 배치에서 모델평가
    
acc = metric.compute()
print(f"Accuracy on all data: {acc}")   

In [36]:
import torch
import torchmetrics

num_classes = 5
metric = torchmetrics.Accuracy(task='multiclass', num_classes=num_classes)

n_batches = 10
for i in range(n_batches):
    preds = torch.rand(10, 5).softmax(dim=-1)
    target = torch.randint(num_classes, (10,))
    
    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc.item()}")  # Note: using `acc.item()` to get a scalar value
    
acc = metric.compute()
print(f"Accuracy on all data: {acc.item()}")


Accuracy on batch 0: 0.0
Accuracy on batch 1: 0.30000001192092896
Accuracy on batch 2: 0.10000000149011612
Accuracy on batch 3: 0.5
Accuracy on batch 4: 0.10000000149011612
Accuracy on batch 5: 0.10000000149011612
Accuracy on batch 6: 0.10000000149011612
Accuracy on batch 7: 0.30000001192092896
Accuracy on batch 8: 0.20000000298023224
Accuracy on batch 9: 0.20000000298023224
Accuracy on all data: 0.1899999976158142


7. 훈련 과정 모니터링

1) 텐서보드 설정
2) 텐서보드에 기록
3) 텐서보드를 사용하여 모델 구조를 살펴본다

In [40]:
import torch
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("/ch2")
num_epochs = 5
for epoch in range(num_epochs):
    model.train() #학습 모드로 전환 (dropout=True)
    batch_loss = 0.0
    
    for i, (x,y) in enumerate(dataloader):
        x,y = x.to(device).float(), y.to(device).float()
        outputs = model(x)
        loss = criterion(outputs, y)
        writer.add_scalar("Loss",loss,epoch) #스칼라 값(오차)를 기록
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
writer.close() #SummaryWriter가 더 이상 필요하지 않으면 close() 메서드 호출

NameError: name 'dataloader' is not defined